# Site
repository: i-dongik
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dongik Shin
title: AI Researcher
email: sdimivy014@gmail.com
website: https://blog.naver.com/i-dongik

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  i-dongik
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: i.dongik
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Dongik and I'm an enthusiastic artificial intelligence researcher. I was a master's student at Korea university, and I am currently looking to study abroad.
  My primary research interest lies in computer vision and machine perception. 
  Specifically, I am eager to explore problems related to bridging gaps between domains and techniques for understanding the decision-making processes of models. 
  Moreover, I am interested in working on how to optimize and apply models in specific fields such as healthcare. 

  In addition to being an AI researcher, I am enthusiastically working toward improvement. I'm still working on my personal page.

# I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Korea University
        caption: Mar 2021 - Feb 2024
        sub_title: M.S. in Computer Science & Engineering
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my master’s program at Korea university, I took on the challenge of entering the field of artificial intelligence for the first time. 
          I conducted research in the area of computer vision using medical data.
          I developed methodology for lesion segmentation in ultrasound images and designed an application with graphical user interface (GUI) to facilitate segmentation tasks. 
          As part of the project, I also designed a pipeline for effective alignment of datasets to ensure compatibility between external and internal datasets.          
      - layout: left
        title: Korea University
        caption: Mar 2015 - Feb 2021
        sub_title: B.E. in Computer Science & Engineering
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Korea university, I learnt most of my key skills about computer science. 
          I thoroughly enjoyed my time on campus and learned a lot, from fundamental theory to application across fields, with information theory being my most memorable and fasinating course work. 

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: SK networks AI Program
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: 
        caption: Oct 2024 - Apr 2025
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            I joined the program focused on developing web applications using large-language models (LLMs). The application project will be uploaded on GitHub.
      - layout: left
        title: Privacy Enhancing Technologies Lab
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Research Intern (undergraduate)
        caption: Sep 2019 - Dec 2019
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            I collaborated with a research team to develop a method for generating pseudo-random numbers using smart contract-based blockchain technology.

      - layout: left
        title: Korean National Police
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Administrative Assistant
        caption: Jan 2017 - Oct 2018
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            I worked as an administrative assistant at the police located in Gyeongju, Gyeongsangbuk-do, South Korea, during my military service.

  - title: Publication # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        # title: 
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   Conferences
        description: | # this will include new lines to allow paragraphs
            - [W.1] Shin, D., Kim, MD, B., & Baek, S. (2023, October). CEmb-SAM: Segment Anything Model with Condition Embedding for Joint Learning from Heterogeneous Datasets. In International Conference on Medical Image Computing and Computer-Assisted Intervention (pp. 275-284). Cham: Springer Nature Switzerland.
            - [J.1] Kim, S. W., Kim, S., Shin, D., Choi, J. H., Sim, J. S., Baek, S., & Yoon, J. S. (2023). Feasibility of artificial intelligence assisted quantitative muscle ultrasound in carpal tunnel syndrome. BMC Musculoskeletal Disorders, 24(1), 524.

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
